import { CategoryGetDto, RecipeDetailsGetDto, ShoppingListDetailsGetDto, TagGetDto } from "api/GET/DTOs";

const categories: ReadonlyArray<CategoryGetDto> = [
  {
    id: 1,
    name: "main",
    color: "#E28930",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-cooking-pot"><path d="M2 12h20"/><path d="M20 12v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8"/><path d="m4 8 16-4"/><path d="m8.86 6.78-.45-1.81a2 2 0 0 1 1.45-2.43l1.94-.48a2 2 0 0 1 2.43 1.46l.45 1.8"/></svg>`,
  },
  {
    id: 2,
    name: "dessert",
    color: "#D785DB",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ice-cream-bowl"><path d="M12 17c5 0 8-2.69 8-6H4c0 3.31 3 6 8 6m-4 4h8m-4-3v3M5.14 11a3.5 3.5 0 1 1 6.71 0"/><path d="M12.14 11a3.5 3.5 0 1 1 6.71 0"/><path d="M15.5 6.5a3.5 3.5 0 1 0-7 0"/></svg>`,
  },
  {
    id: 3,
    name: "breakfast/supper",
    color: "#55B5C6",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sandwich"><path d="m2.37 11.223 8.372-6.777a2 2 0 0 1 2.516 0l8.371 6.777"/><path d="M21 15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-5.25"/><path d="M3 15a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h9"/><path d="m6.67 15 6.13 4.6a2 2 0 0 0 2.8-.4l3.15-4.2"/><rect width="20" height="4" x="2" y="11" rx="1"/></svg>`,
  },
  {
    id: 4,
    name: "soup",
    color: "#DAB436",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-soup"><path d="M12 21a9 9 0 0 0 9-9H3a9 9 0 0 0 9 9Z"/><path d="M7 21h10"/><path d="M19.5 12 22 6"/><path d="M16.25 3c.27.1.8.53.75 1.36-.06.83-.93 1.2-1 2.02-.05.78.34 1.24.73 1.62"/><path d="M11.25 3c.27.1.8.53.74 1.36-.05.83-.93 1.2-.98 2.02-.06.78.33 1.24.72 1.62"/><path d="M6.25 3c.27.1.8.53.75 1.36-.06.83-.93 1.2-1 2.02-.05.78.34 1.24.74 1.62"/></svg>`,
  },
  {
    id: 5,
    name: "sauce",
    color: "#CB4F39",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dessert"><circle cx="12" cy="4" r="2"/><path d="M10.2 3.2C5.5 4 2 8.1 2 13a2 2 0 0 0 4 0v-1a2 2 0 0 1 4 0v4a2 2 0 0 0 4 0v-4a2 2 0 0 1 4 0v1a2 2 0 0 0 4 0c0-4.9-3.5-9-8.2-9.8"/><path d="M3.2 14.8a9 9 0 0 0 17.6 0"/></svg>`,
  },
  {
    id: 6,
    name: "alcohol",
    color: "#5D69E4",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-wine"><path d="M8 22h8"/><path d="M7 10h10"/><path d="M12 15v7"/><path d="M12 15a5 5 0 0 0 5-5c0-2-.5-4-2-8H9c-1.5 4-2 6-2 8a5 5 0 0 0 5 5Z"/></svg>`,
  },
  {
    id: 7,
    name: "other",
    color: "#9F9F9F",
    symbol: String.raw`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-croissant"><path d="m4.6 13.11 5.79-3.21c1.89-1.05 4.79 1.78 3.71 3.71l-3.22 5.81C8.8 23.16.79 15.23 4.6 13.11Z"/><path d="m10.5 9.5-1-2.29C9.2 6.48 8.8 6 8 6H4.5C2.79 6 2 6.5 2 8.5a7.71 7.71 0 0 0 2 4.83"/><path d="M8 6c0-1.55.24-4-2-4-2 0-2.5 2.17-2.5 4"/><path d="m14.5 13.5 2.29 1c.73.3 1.21.7 1.21 1.5v3.5c0 1.71-.5 2.5-2.5 2.5a7.71 7.71 0 0 1-4.83-2"/><path d="M18 16c1.55 0 4-.24 4 2 0 2-2.17 2.5-4 2.5"/></svg>`,
  },
];

const tags: ReadonlyArray<TagGetDto> = [
  { id: 1, name: "vegan" },
  { id: 2, name: "vegetarian" },
  { id: 3, name: "sweet" },
  { id: 4, name: "spicy" },
  { id: 5, name: "sour" },
  { id: 6, name: "chicken" },
  { id: 7, name: "beef" },
  { id: 8, name: "pork" },
  { id: 9, name: "light" },
  { id: 10, name: "heavy" },
  { id: 11, name: "fast" },
  { id: 12, name: "healthy" },
  { id: 13, name: "low-sugar" },
  { id: 14, name: "mexican" },
  { id: 15, name: "italian" },
  { id: 16, name: "polish" },
  { id: 17, name: "drink" },
  { id: 18, name: "shots" },
];

const recipes: ReadonlyArray<RecipeDetailsGetDto> = [
  {
    id: 1,
    name: "Beef burritos",
    category: categories[0],
    tags: [tags[3], tags[6], tags[13]],
    imageSrc: "assets/images/1-beef-burrito.jpg",
    ingredients: [
      { id: 1, name: "sunflower oil", amount: { value: "2", unit: "tbsp" }, checked: false },
      { id: 2, name: "onion", amount: { value: "1", unit: null }, checked: false },
      { id: 3, name: "garlic cloves", amount: { value: "4", unit: null }, checked: false },
      { id: 4, name: "ground cumin", amount: { value: "1", unit: "tbsp" }, checked: false },
      { id: 5, name: "ground coriander", amount: { value: "1", unit: "tbsp" }, checked: false },
      { id: 6, name: "cayenne pepper", amount: { value: "pinch", unit: null }, checked: false },
      { id: 7, name: "dried oregano", amount: { value: "1", unit: "tsp" }, checked: false },
      { id: 8, name: "beef mince", amount: { value: "500", unit: "g" }, checked: false },
      { id: 9, name: "golden caster sugar", amount: { value: "pinch", unit: null }, checked: false },
      { id: 10, name: "wine vinegar", amount: { value: "1", unit: "tbsp" }, checked: false },
      { id: 11, name: "chopped tomatoes", amount: { value: "400", unit: "g" }, checked: false },
      { id: 12, name: "black beans", amount: { value: "400", unit: "g" }, checked: false },
      { id: 13, name: "flour or corn tortillas", amount: { value: "8", unit: null }, checked: false },
      { id: 14, name: "cooked rice", amount: { value: "500", unit: "g" }, checked: false },
      { id: 15, name: "sliced avocado", amount: { value: "some", unit: null }, checked: false },
    ],
    description: `<h1 class="heading-1">Step 1</h1><p></p><p>Heat the oil in a large pan – a casserole is ideal. Fry the onions for 8 mins, then add the garlic, spices and oregano and cook for 1 min. Crumble over the mince and sizzle for 5 mins, stirring, until browned. Stir in the sugar and leave for a minute, then splash in the vinegar and pour in the tomatoes.</p><p></p><h1 class="heading-1">Step 2</h1><p></p><p>Simmer for 5 mins then tip in the beans and the water from the can. Season, stir and simmer everything for 20 mins until the beef is in a thick gravy. The sauce can be prepared up to 2 days ahead, chilled and reheated with a splash of water or frozen for 6 months.</p><p></p><h1 class="heading-1">Step 3</h1><p></p><p>To make the burritos, heat the tortillas following pack instructions. Pile some rice and beef sauce along each tortilla and scatter over your choice of topping. Fold over the ends and roll up to seal. Secure by wrapping with foil if you want. Eat immediately.</p><p></p><p></p><p><em>Source: https://www.bbcgoodfood.com/recipes/easy-beef-burritos</em></p>`,
    creationDate: "03-01-2025",
    updateDate: "04-01-2025",
  },
  {
    id: 2,
    name: "Carbonara",
    category: categories[0],
    tags: [tags[7], tags[10], tags[14]],
    imageSrc: "assets/images/2-carbonara.jpg",
    ingredients: [
      {
        id: 16,
        name: "pancetta",
        amount: { value: "100", unit: "g" },
        checked: false,
      },
      {
        id: 17,
        name: "pecorino cheese",
        amount: { value: "50", unit: "g" },
        checked: false,
      },
      {
        id: 18,
        name: "parmesan",
        amount: { value: "50", unit: "g" },
        checked: false,
      },
      {
        id: 19,
        name: "large eggs",
        amount: { value: "3", unit: null },
        checked: false,
      },
      {
        id: 20,
        name: "spaghetti",
        amount: { value: "350", unit: "g" },
        checked: false,
      },
      {
        id: 21,
        name: "plump garlic cloves",
        amount: { value: "2", unit: null },
        checked: false,
      },
      {
        id: 22,
        name: "unsalted butter",
        amount: { value: "50", unit: "g" },
        checked: false,
      },
      {
        id: 23,
        name: "sea salt",
        amount: { value: "pinch", unit: null },
        checked: false,
      },
      {
        id: 24,
        name: "ground black pepper",
        amount: { value: "pinch", unit: null },
        checked: false,
      },
    ],
    description:
      '<h1 class="heading-1"><strong>Step 1</strong></h1><p></p><p>Put a large <u>saucepan</u> of water on to boil.</p><p></p><h1 class="heading-1"><strong>Step 2</strong></h1><p></p><p>Finely <u>chop</u> the 100g pancetta, having first removed any rind. Finely grate 50g pecorino cheese and 50g parmesan and mix them together.</p><p></p><h1 class="heading-1"><strong>Step 3</strong></h1><p></p><p><u>Beat</u> the 3 large eggs in a medium bowl and season with a little freshly grated black pepper. Set everything aside.</p><p></p><h1 class="heading-1"><strong>Step 4</strong></h1><p></p><p>Add 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked).</p><p></p><h1 class="heading-1"><strong>Step 5</strong></h1><p></p><p><u>Squash</u> 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.</p><p></p><h1 class="heading-1"><strong>Step 6</strong></h1><p></p><p>While the spaghetti is cooking, fry the pancetta with the garlic. Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic.</p><p></p><h1 class="heading-1"><strong>Step 7</strong></h1><p></p><p>Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp. The garlic has now imparted its flavour, so take it out with a slotted spoon and discard.</p><p></p><h1 class="heading-1"><strong>Step 8</strong></h1><p></p><p>Keep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta. Don’t worry if a little water drops in the pan as well (you want this to happen) and don’t throw the pasta water away yet.</p><p></p><h1 class="heading-1"><strong>Step 9</strong></h1><p></p><p>Mix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later.</p><p></p><h1 class="heading-1"><strong>Step 10</strong></h1><p></p><p>Take the pan of spaghetti and pancetta off the heat. Now quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn’t scramble, and everything is coated.</p><p></p><h1 class="heading-1"><strong>Step 11</strong></h1><p></p><p>Add extra pasta cooking water to keep it saucy (several tablespoons should do it). You don’t want it wet, just moist. Season with a little salt, if needed.</p><p></p><h1 class="heading-1"><strong>Step 12</strong></h1><p></p><p>Use a long-pronged fork to twist the pasta on to the serving plate or bowl. Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper. If the dish does get a little dry before serving, splash in some more hot pasta water and the glossy sauciness will be revived.</p><p></p><p><em>Source: https://www.bbcgoodfood.com/recipes/ultimate-spaghetti-carbonara-recipe</em></p>',
    creationDate: "03-01-2025",
    updateDate: "04-01-2025",
  },
  {
    id: 3,
    name: "Margarita",
    category: categories[5],
    tags: [tags[4], tags[16]],
    imageSrc: "assets/images/3-margarita.jpg",
    ingredients: [
      {
        id: 25,
        name: "ice",
        amount: { value: null, unit: null },
        checked: false,
      },
      {
        id: 26,
        name: "tequila",
        amount: { value: "50", unit: "ml" },
        checked: false,
      },
      {
        id: 27,
        name: "lime juice",
        amount: { value: "25", unit: "ml" },
        checked: false,
      },
      {
        id: 28,
        name: "triple sec",
        amount: { value: "20", unit: "ml" },
        checked: false,
      },
      {
        id: 29,
        name: "salt",
        amount: { value: null, unit: null },
        checked: false,
      },
      {
        id: 30,
        name: "lime wedges",
        amount: { value: "2", unit: null },
        checked: false,
      },
    ],
    description:
      '<h1 class="heading-1"><strong>Step 1</strong></h1><p></p><p>Sprinkle a few teaspoons of salt over the surface of a small plate or saucer. Rub one wedge of lime along the rim of a tumbler and then dip it into the salt so</p><p>that the entire rim is covered.</p><p></p><h1 class="heading-1"><strong>Step 2</strong></h1><p></p><p>Fill a cocktail shaker with ice, then add the tequila, lime juice and triple sec. Shake until the outside of the shaker feels cold.</p><p></p><h1 class="heading-1"><strong>Step 3</strong></h1><p></p><p>Strain the mix into the prepared glass over fresh ice. Serve with a wedge of lime.</p><p></p><p><em>Source: https://www.bbcgoodfood.com/recipes/tequila-classic-margarita</em></p>',
    creationDate: "03-01-2025",
    updateDate: "04-01-2025",
  },
  {
    id: 4,
    name: "Oatmeal",
    category: categories[2],
    tags: [tags[1], tags[2], tags[8], tags[10], tags[11]],
    imageSrc: "assets/images/4-oatmeal.jpg",
    ingredients: [
      {
        id: 31,
        name: "water",
        amount: { value: "1", unit: "cup" },
        checked: false,
      },
      {
        id: 32,
        name: "whole rolled oats",
        amount: { value: "1/2", unit: "cup" },
        checked: false,
      },
      {
        id: 33,
        name: "sea salt",
        amount: { value: "pinch", unit: null },
        checked: false,
      },
      {
        id: 34,
        name: "cinnamon",
        amount: { value: null, unit: null },
        checked: false,
      },
      {
        id: 35,
        name: "honey",
        amount: { value: null, unit: null },
        checked: false,
      },
      {
        id: 36,
        name: "nuts",
        amount: { value: null, unit: null },
        checked: false,
      },
      {
        id: 37,
        name: "fruits",
        amount: { value: null, unit: null },
        checked: false,
      },
    ],
    description:
      '<h1 class="heading-1">Step 1</h1><p></p><p>In a small pot, stir together the water, oats, and salt. Bring to a boil over medium-high heat, then reduce the heat to medium-low. Cook, stirring occasionally, for 2 to 5 minutes, or until the oatmeal is thick and creamy. Stir in a pinch of cinnamon, nutmeg, and/or cardamom, if desired. Remove from heat and let stand for 1 minute. Serve hot with honey or maple syrup, if desired.</p><p></p><h1 class="heading-1">Step 2</h1><p></p><p>To make the Apple &amp; Tart Cherry variation, top with sliced apples, tart cherries, and almonds.</p><p></p><h1 class="heading-1">Step 3</h1><p></p><p>To make the Blueberry &amp; Coconut variation, top with blueberries, orange zest, a scoop of Greek yogurt, chia seeds, and coconut flakes.</p><p></p><p><em>Source: https://www.loveandlemons.com/how-to-make-oatmeal/</em></p>',
    creationDate: "03-01-2025",
    updateDate: "04-01-2025",
  },
  {
    id: 5,
    name: "Cheesecake",
    category: categories[1],
    tags: [tags[1], tags[2], tags[15]],
    imageSrc: "assets/images/5-cheesecake.jpg",
    ingredients: [
      {
        id: 38,
        name: "wholewheat flour",
        amount: { value: "250", unit: "g" },
        checked: false,
      },
      {
        id: 39,
        name: "sour cream 18%",
        amount: { value: "1", unit: "tbsp" },
        checked: false,
      },
      {
        id: 40,
        name: "Farmer’s Cheese, full fat",
        amount: { value: "1", unit: "kg" },
        checked: false,
      },
      {
        id: 41,
        name: "eggs",
        amount: { value: "5", unit: null },
        checked: false,
      },
      {
        id: 42,
        name: "sugar",
        amount: { value: "200", unit: "g" },
        checked: false,
      },
      {
        id: 43,
        name: "vanilla extract",
        amount: { value: "2", unit: "tbsp" },
        checked: false,
      },
      {
        id: 44,
        name: "butter",
        amount: { value: "220", unit: "g" },
        checked: false,
      },
      {
        id: 45,
        name: "potato starch (optional)",
        amount: { value: "2", unit: "tbsp" },
        checked: false,
      },
      {
        id: 46,
        name: "candied orange peel chopped",
        amount: { value: "2", unit: "tbsp" },
        checked: false,
      },
      {
        id: 47,
        name: "raisins (optional)",
        amount: { value: "2", unit: "tbsp" },
        checked: false,
      },
      {
        id: 48,
        name: "powdered/icing sugar",
        amount: { value: "4", unit: "tbsp" },
        checked: false,
      },
    ],
    description:
      '<h1 class="heading-1">Step 1</h1><p></p><p>Take the ingredients (for the cheese layer only!) out of the fridge 2-3 hours before baking. They should be at a room temperature.</p><p></p><h1 class="heading-1">Step 2</h1><p></p><p>Grab a large bowl. Drop in all the shortcrust ingredients. Chop the butter roughly with a knife. Knead until all the ingredients are combined and you can’t feel any major lumps. Form a dough ball.</p><p></p><h1 class="heading-1">Step 3</h1><p></p><p>Wrap the bowl with cling film and place in the fridge for 20-30 minutes.</p><p></p><h1 class="heading-1">Step 4</h1><p></p><p>In the meantime, let’s make the cheese layer. Grind the farmer’s cheese with a tool of your choice: meat grinder (smallest holes), potato ricer or a blender. When using a meat grinder, grind the cheese at least 2 times. The mass should be smooth and lump-free. Set the cheese aside, you’ll need it in a minute.</p><p></p><h1 class="heading-1">Step 5</h1><p></p><p>Preheat the oven to 360°F (180°C). Line a round baking tin (I’ve used 10 inch / 25cm in diameter, with a loose base) with parchment paper. Grease the edges.&nbsp;</p><p></p><h1 class="heading-1">Step 6</h1><p></p><p>Remove the dough from the fridge. Roll it out to fit the baking tin. I just grab small chunks of dough and line the pan by hand, pressing with my fingers as I go, until I have an even layer of pastry.</p><p></p><h1 class="heading-1">Step 7</h1><p></p><p>Bake for 15 minutes until lightly golden, then remove from the oven - but keep the oven on.</p><p></p><h1 class="heading-1">Step 8</h1><p></p><p>Grab a large bowl (sized at 2 quart / 2 litre should be enough). Add 1 cup (200 g) sugar, 2 teaspoons of vanilla extract and 3 egg yolks and mix with an electric mixer for 3 minutes until combined.&nbsp;</p><p></p><h1 class="heading-1">Step 9</h1><p></p><p>Add ground cheese to the bowl, add softened butter. (Optional step) If you feel that the cheese mass is loose, add 2 tablespoons of potato starch. Mix again with a mixer for 3-4 minutes.</p><p></p><h1 class="heading-1">Step 10</h1><p></p><p>In a separate container, beat 5 egg whites until stiff. I use a mixer, but you can do it by hand if you’re brave.</p><p></p><h1 class="heading-1">Step 11</h1><p></p><p>Grab a spoon or a spatula and gently blend the egg whites with our cheese mass. The key is not to over-mix it.</p><p></p><h1 class="heading-1">Step 12</h1><p></p><p>Add 2 tablespoons of chopped candied orange peel, together with 2 tablespoons of raisins. Blend them in for a few seconds.&nbsp;</p><p></p><h1 class="heading-1">Step 13</h1><p></p><p>Pour the cheese mass on top of the pre-baked shortcrust pastry. Bake for 60 minutes at 360°F (180°C), switching off any fan-assisted functions.&nbsp;</p><p></p><h1 class="heading-1">Step 14</h1><p></p><p>Once the time is up, switch off the heat, but leave the cheesecake inside for another 30 minutes. After that time, open the oven slightly and leave the cake inside until the oven is completely cooled.</p><p></p><h1 class="heading-1">Step 15</h1><p></p><p>Once cooled, sprinkle with powdered sugar.&nbsp;</p><p></p><p><em>Source: https://www.polonist.com/polish-cheesecake-sernik/</em></p>',
    creationDate: "03-01-2025",
    updateDate: "04-01-2025",
  },
];

const createDateWithDaysOffset = (days: number): string => {
  const date = new Date();
  date.setDate(new Date().getDate() + days);
  return date.toString();
};

const shoppingLists: ReadonlyArray<ShoppingListDetailsGetDto> = [
  {
    id: 1,
    name: "groceries",
    autoDelete: true,
    creationDate: new Date().toString(),
    updateDate: new Date().toString(),
    sublists: [
      {
        id: 1,
        name: "Manual sublist",
        recipeId: null,
        count: 1,
        items: [
          { id: 1, name: "carrots", amount: { value: "0.5", unit: "kg" }, checked: false },
          { id: 2, name: "onion", amount: { value: "3", unit: null }, checked: false },
          { id: 3, name: "cheese", amount: { value: "1", unit: "pack" }, checked: false },
          { id: 4, name: "bread", amount: { value: "1", unit: null }, checked: false },
        ],
      },
      {
        id: 2,
        name: "Beef burritos",
        recipeId: 1,
        count: 1,
        items: [
          { id: 16, name: "sunflower oil", amount: { value: "2", unit: "tbsp" }, checked: false },
          { id: 17, name: "onion", amount: { value: "1", unit: null }, checked: false },
          { id: 18, name: "garlic cloves", amount: { value: "4", unit: null }, checked: false },
          { id: 19, name: "ground cumin", amount: { value: "1", unit: "tbsp" }, checked: false },
          { id: 5, name: "ground coriander", amount: { value: "1", unit: "tbsp" }, checked: false },
          { id: 6, name: "cayenne pepper", amount: { value: "pinch", unit: null }, checked: false },
          { id: 7, name: "dried oregano", amount: { value: "1", unit: "tsp" }, checked: false },
          { id: 8, name: "beef mince", amount: { value: "500", unit: "g" }, checked: false },
          { id: 9, name: "golden caster sugar", amount: { value: "pinch", unit: null }, checked: false },
          { id: 10, name: "wine vinegar", amount: { value: "1", unit: "tbsp" }, checked: false },
          { id: 11, name: "chopped tomatoes", amount: { value: "400", unit: "g" }, checked: false },
          { id: 12, name: "black beans", amount: { value: "400", unit: "g" }, checked: false },
          { id: 13, name: "flour or corn tortillas", amount: { value: "8", unit: null }, checked: false },
          { id: 14, name: "cooked rice", amount: { value: "500", unit: "g" }, checked: false },
          { id: 15, name: "sliced avocado", amount: { value: "some", unit: null }, checked: false },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "christmas presents",
    autoDelete: false,
    creationDate: createDateWithDaysOffset(-20),
    updateDate: createDateWithDaysOffset(-20),
    sublists: [
      {
        id: 1,
        name: "Manual sublist",
        recipeId: null,
        count: 1,
        items: [
          { id: 1, name: "christmas jumper", amount: { value: null, unit: null }, checked: false },
          { id: 2, name: "Nintendo game", amount: { value: null, unit: null }, checked: false },
          { id: 3, name: "Thermos", amount: { value: null, unit: null }, checked: false },
          { id: 4, name: "Electric kettle", amount: { value: null, unit: null }, checked: false },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "groceries - older list",
    autoDelete: true,
    creationDate: createDateWithDaysOffset(-10),
    updateDate: createDateWithDaysOffset(-10),
    sublists: [
      {
        id: 1,
        name: "Manual sublist",
        recipeId: null,
        count: 1,
        items: [
          { id: 1, name: "carrots", amount: { value: "0.5", unit: "kg" }, checked: false },
          { id: 2, name: "onion", amount: { value: "3", unit: null }, checked: false },
          { id: 3, name: "cheese", amount: { value: "1", unit: "pack" }, checked: false },
          { id: 4, name: "bread", amount: { value: "1", unit: null }, checked: false },
        ],
      },
      {
        id: 2,
        name: "Beef burritos",
        recipeId: 1,
        count: 1,
        items: [
          {
            id: 38,
            name: "wholewheat flour",
            amount: { value: "250", unit: "g" },
            checked: false,
          },
          {
            id: 39,
            name: "sour cream 18%",
            amount: { value: "1", unit: "tbsp" },
            checked: false,
          },
          {
            id: 40,
            name: "Farmer’s Cheese, full fat",
            amount: { value: "1", unit: "kg" },
            checked: false,
          },
          {
            id: 41,
            name: "eggs",
            amount: { value: "5", unit: null },
            checked: false,
          },
          {
            id: 42,
            name: "sugar",
            amount: { value: "200", unit: "g" },
            checked: false,
          },
          {
            id: 43,
            name: "vanilla extract",
            amount: { value: "2", unit: "tbsp" },
            checked: false,
          },
          {
            id: 44,
            name: "butter",
            amount: { value: "220", unit: "g" },
            checked: false,
          },
          {
            id: 45,
            name: "potato starch (optional)",
            amount: { value: "2", unit: "tbsp" },
            checked: false,
          },
          {
            id: 46,
            name: "candied orange peel chopped",
            amount: { value: "2", unit: "tbsp" },
            checked: false,
          },
          {
            id: 47,
            name: "raisins (optional)",
            amount: { value: "2", unit: "tbsp" },
            checked: false,
          },
          {
            id: 48,
            name: "powdered/icing sugar",
            amount: { value: "4", unit: "tbsp" },
            checked: false,
          },
        ],
      },
      {
        id: 3,
        name: "Margarita",
        recipeId: 3,
        count: 1,
        items: [
          {
            id: 25,
            name: "ice",
            amount: { value: null, unit: null },
            checked: false,
          },
          {
            id: 26,
            name: "tequila",
            amount: { value: "50", unit: "ml" },
            checked: false,
          },
          {
            id: 27,
            name: "lime juice",
            amount: { value: "25", unit: "ml" },
            checked: false,
          },
          {
            id: 28,
            name: "triple sec",
            amount: { value: "20", unit: "ml" },
            checked: false,
          },
          {
            id: 29,
            name: "salt",
            amount: { value: null, unit: null },
            checked: false,
          },
          {
            id: 30,
            name: "lime wedges",
            amount: { value: "2", unit: null },
            checked: false,
          },
        ],
      },
    ],
  },
];

const dbData = { categories, tags, recipes, shoppingLists };
export default dbData;
